version: "3"
services:
  nginx:
    build: nginx
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/symfony
    working_dir: /var/www/symfony
  php-fpm:
    build: php-fpm
    volumes:
      - ./app:/var/www/symfony
  symfony:
    build: symfony
    user: "1000"
    volumes:
      - ./app:/var/www/symfony
      - ./symfony/composer_cache:/var/www/.composer/cache
  mariadb:
    image: mariadb:10.3
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=symfony_user
      - MYSQL_PASSWORD=changemetoo
  redis:
    image: redis:4
    volumes:
      - redisdata:/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  elk:
    image: willdurand/elk
    ports:
      - 8080:80
    volumes:
      - ./elk/logstash:/etc/logstash
      - ./elk/logstash/patterns:/opt/logstash/patterns
      - ./app:/var/www/symfony
volumes:
  esdata:
    driver: local
  redisdata:
    driver: local