version: "3"
services:
  nginx:
    build: nginx
    ports:
      - 80:80
    volumes:
      - ${APP_PATH}:/var/www/symfony
    working_dir: /var/www/symfony
  php:
    build: php-fpm
    volumes:
      - ${APP_PATH}:/var/www/symfony
      - ./composer_cache:/var/www/.composer/cache
    environment:
      - PHP_IDE_CONFIG=serverName=symfony.dev # Replace symfony.dev with the server name you've created in your IDE
  mariadb:
    image: mariadb:10.3
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  redis:
    image: redis:4
    volumes:
      - redisdata:/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  elk:
    image: willdurand/elk
    ports:
      - 8080:80
    volumes:
      - ./elk/logstash:/etc/logstash
      - ./elk/logstash/patterns:/opt/logstash/patterns
      - ${APP_PATH}:/var/www/symfony
volumes:
  esdata:
    driver: local
  redisdata:
    driver: local